"""initial schema

Revision ID: 484e47b6352a
Revises: 
Create Date: 2026-05-02 07:49:13.579040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '484e47b6352a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('use_case', sa.Enum('monthly_report', 'weekly_summary', 'theme_suggestion', 'content_draft', 'compliance_check', 'inquiry_structuring', 'eeat_analysis', 'citation_opportunity', name='ai_use_case'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('use_case', 'version', name='uq_prompt_templates_use_case_version')
    )
    op.create_table('tenants',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('compliance_type', sa.Enum('general', 'lawyer', 'medical', 'realestate', 'finance', name='compliance_type'), server_default='general', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'client', name='user_role'), server_default='client', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ai_provider_configs',
    sa.Column('use_case', sa.Enum('monthly_report', 'weekly_summary', 'theme_suggestion', 'content_draft', 'compliance_check', 'inquiry_structuring', 'eeat_analysis', 'citation_opportunity', name='ai_use_case'), nullable=False),
    sa.Column('provider', sa.Enum('gemini', 'claude', 'openai', 'perplexity', name='ai_provider'), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('prompt_template_id', sa.UUID(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), server_default='0.70', nullable=False),
    sa.Column('max_tokens', sa.Integer(), server_default='2000', nullable=False),
    sa.Column('fallback_provider', sa.Enum('gemini', 'claude', 'openai', 'perplexity', name='ai_provider'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'use_case', name='uq_ai_provider_configs_tenant_use_case')
    )
    op.create_index(op.f('ix_ai_provider_configs_tenant_id'), 'ai_provider_configs', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_table', sa.Text(), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_tenant_created', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('author_profiles',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('job_title', sa.Text(), nullable=True),
    sa.Column('works_for', sa.Text(), nullable=True),
    sa.Column('alumni_of', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('expertise', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('publications', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('speaking_engagements', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('awards', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('bio_short', sa.Text(), nullable=True),
    sa.Column('bio_long', sa.Text(), nullable=True),
    sa.Column('social_profiles', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_profiles_tenant_id'), 'author_profiles', ['tenant_id'], unique=False)
    op.create_table('competitors',
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('brand_name', sa.Text(), nullable=True),
    sa.Column('rss_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_tenant_id'), 'competitors', ['tenant_id'], unique=False)
    op.create_table('inquiries',
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('company_size', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('source_channel', sa.Enum('web', 'email', 'phone', 'ai', 'other', name='inquiry_source'), nullable=False),
    sa.Column('ai_origin', sa.Enum('chatgpt', 'claude', 'perplexity', 'gemini', 'aio', name='ai_origin'), nullable=True),
    sa.Column('status', sa.Enum('new', 'in_progress', 'contracted', 'lost', name='inquiry_status'), server_default='new', nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inquiries_tenant_id'), 'inquiries', ['tenant_id'], unique=False)
    op.create_index('ix_inquiries_tenant_received', 'inquiries', ['tenant_id', 'received_at'], unique=False)
    op.create_table('job_execution_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('job_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'success', 'failed', 'skipped', name='job_status'), nullable=False),
    sa.Column('attempt_no', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_execution_logs_tenant_id'), 'job_execution_logs', ['tenant_id'], unique=False)
    op.create_index('ix_job_logs_name_started', 'job_execution_logs', ['job_name', 'started_at'], unique=False)
    op.create_table('kpi_logs',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('avg_position', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_citation_count', sa.Integer(), nullable=True),
    sa.Column('named_search_count', sa.Integer(), nullable=True),
    sa.Column('inquiries_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'date', name='uq_kpi_logs_tenant_date')
    )
    op.create_index('ix_kpi_logs_tenant_date', 'kpi_logs', ['tenant_id', 'date'], unique=False)
    op.create_index(op.f('ix_kpi_logs_tenant_id'), 'kpi_logs', ['tenant_id'], unique=False)
    op.create_table('reports',
    sa.Column('period', sa.CHAR(length=7), nullable=False),
    sa.Column('report_type', sa.Text(), nullable=False),
    sa.Column('summary_html', sa.Text(), nullable=True),
    sa.Column('action_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'period', 'report_type', name='uq_reports_tenant_period_type')
    )
    op.create_index(op.f('ix_reports_tenant_id'), 'reports', ['tenant_id'], unique=False)
    op.create_table('target_queries',
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('cluster_id', sa.Text(), nullable=True),
    sa.Column('priority', sa.SmallInteger(), server_default='3', nullable=False),
    sa.Column('expected_conversion', sa.SmallInteger(), server_default='3', nullable=False),
    sa.Column('search_intent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'query_text', name='uq_target_queries_tenant_text')
    )
    op.create_index('ix_target_queries_tenant_active', 'target_queries', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_target_queries_tenant_id'), 'target_queries', ['tenant_id'], unique=False)
    op.create_table('tenant_credentials',
    sa.Column('provider', sa.Enum('gsc', 'ga4', 'wordpress', 'resend', 'serpapi', 'gemini_ai_engine', 'gemini_citation_monitor', 'openai', 'anthropic', 'perplexity', 'facebook', name='credential_provider'), nullable=False),
    sa.Column('encrypted_data', sa.LargeBinary(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', name='uq_tenant_credentials_tenant_provider')
    )
    op.create_index(op.f('ix_tenant_credentials_tenant_id'), 'tenant_credentials', ['tenant_id'], unique=False)
    op.create_table('user_tenants',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tenant_id')
    )
    op.create_table('citation_logs',
    sa.Column('query_id', sa.UUID(), nullable=False),
    sa.Column('llm_provider', sa.Enum('chatgpt', 'claude', 'perplexity', 'gemini', 'aio', name='llm_provider'), nullable=False),
    sa.Column('query_date', sa.Date(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('cited_urls', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('self_cited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('competitor_cited', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['target_queries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_logs_tenant_id'), 'citation_logs', ['tenant_id'], unique=False)
    op.create_index('ix_citation_logs_tenant_query_date', 'citation_logs', ['tenant_id', 'query_id', 'query_date'], unique=False)
    op.create_table('contents',
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ai_generating', 'review', 'published', 'archived', name='content_status'), server_default='draft', nullable=False),
    sa.Column('pillar_id', sa.Text(), nullable=True),
    sa.Column('cluster_id', sa.Text(), nullable=True),
    sa.Column('schema_score', sa.SmallInteger(), nullable=True),
    sa.Column('draft_md', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wp_post_id', sa.BigInteger(), nullable=True),
    sa.Column('primary_author_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_author_id'], ['author_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'url', name='uq_contents_tenant_url')
    )
    op.create_index(op.f('ix_contents_tenant_id'), 'contents', ['tenant_id'], unique=False)
    op.create_index('ix_contents_tenant_status', 'contents', ['tenant_id', 'status', 'published_at'], unique=False)
    op.create_table('content_metrics',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sessions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('citations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'date', name='uq_content_metrics_content_date')
    )
    op.create_index('ix_content_metrics_tenant_date', 'content_metrics', ['tenant_id', 'date'], unique=False)
    op.create_index(op.f('ix_content_metrics_tenant_id'), 'content_metrics', ['tenant_id'], unique=False)
    op.create_table('schema_audit_logs',
    sa.Column('content_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('audit_date', sa.Date(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('raw_jsonld', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_audit_logs_tenant_id'), 'schema_audit_logs', ['tenant_id'], unique=False)
    op.create_index('ix_schema_audit_tenant_date', 'schema_audit_logs', ['tenant_id', 'audit_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_schema_audit_tenant_date', table_name='schema_audit_logs')
    op.drop_index(op.f('ix_schema_audit_logs_tenant_id'), table_name='schema_audit_logs')
    op.drop_table('schema_audit_logs')
    op.drop_index(op.f('ix_content_metrics_tenant_id'), table_name='content_metrics')
    op.drop_index('ix_content_metrics_tenant_date', table_name='content_metrics')
    op.drop_table('content_metrics')
    op.drop_index('ix_contents_tenant_status', table_name='contents')
    op.drop_index(op.f('ix_contents_tenant_id'), table_name='contents')
    op.drop_table('contents')
    op.drop_index('ix_citation_logs_tenant_query_date', table_name='citation_logs')
    op.drop_index(op.f('ix_citation_logs_tenant_id'), table_name='citation_logs')
    op.drop_table('citation_logs')
    op.drop_table('user_tenants')
    op.drop_index(op.f('ix_tenant_credentials_tenant_id'), table_name='tenant_credentials')
    op.drop_table('tenant_credentials')
    op.drop_index(op.f('ix_target_queries_tenant_id'), table_name='target_queries')
    op.drop_index('ix_target_queries_tenant_active', table_name='target_queries')
    op.drop_table('target_queries')
    op.drop_index(op.f('ix_reports_tenant_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_kpi_logs_tenant_id'), table_name='kpi_logs')
    op.drop_index('ix_kpi_logs_tenant_date', table_name='kpi_logs')
    op.drop_table('kpi_logs')
    op.drop_index('ix_job_logs_name_started', table_name='job_execution_logs')
    op.drop_index(op.f('ix_job_execution_logs_tenant_id'), table_name='job_execution_logs')
    op.drop_table('job_execution_logs')
    op.drop_index('ix_inquiries_tenant_received', table_name='inquiries')
    op.drop_index(op.f('ix_inquiries_tenant_id'), table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index(op.f('ix_competitors_tenant_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_author_profiles_tenant_id'), table_name='author_profiles')
    op.drop_table('author_profiles')
    op.drop_index('ix_audit_logs_tenant_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_provider_configs_tenant_id'), table_name='ai_provider_configs')
    op.drop_table('ai_provider_configs')
    op.drop_table('users')
    op.drop_table('tenants')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###

    # autogenerate が拾わない ENUM 型を明示的に drop
    for enum_name in [
        "ai_origin",
        "ai_provider",
        "ai_use_case",
        "compliance_type",
        "content_status",
        "credential_provider",
        "inquiry_source",
        "inquiry_status",
        "job_status",
        "llm_provider",
        "user_role",
    ]:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
